name: Default CI Pipeline

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    workflow_dispatch:
jobs:
    setup:
        name: Install dependencies and run build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install
              run: npm ci
            - name: Build
              run: npm run build
    prettier:
        name: Check coding style
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: Nerixyz/actionsx-prettier@v3-adj
              with:
                  args: --check .
